loglevel: debug

navidrome:
  baseurl: "https://music.bsgb.nl:443"
  user: "bond"
  password: "Rei77GER"
  tlsskipverify: false

sync:
  musicpath: "testdata/"
  prefer: "local"
  remotepathprefix: "/share/Music"
  searchinterval: "100ms"
  metadata:
    ratings: true
    playstats: true
    stars: false
  stars:
    prefer: ""
    tag: "FAVORITE"

playlists:
  path: "testdata/"
  musicpath: ""
  remotepathprefix: "/share/Music"
  prefer: "local"
  format: "m3u8"
  public: false
  removemissing: false
  onunmatched: "error"
  exportpaths: "relative"
