loglevel: debug

navidrome:
  baseurl: "https://music.bsgb.nl:443"
  user: "bond"
  password: "Rei77GER"
  tlsskipverify: false

sync:
  musicpath: "/mnt/extra-ssd/dev/projects/go-navidrome-ratings-sync/testdata/"
  prefer: "local"
  remotepathprefix: "/share/Music"
